### ISSUE TITLE
Requires redux-mock-store?

### ISSUE THREAD

**Issue by VoltiSubito** [mvolkmann/redux-easy#3]
Upgrading dependencies of my React app (including redux-easy), I'm now getting this error:

```
Failed to compile.

./node_modules/redux-easy/lib/redux-easy.js
Module not found: Can't resolve 'redux-mock-store' in '/home/schindlerj/src/lennox-prism/engineering-tool/node_modules/redux-easy/lib'
```

If it requires redux-mock-store, it should probably list it as a dependency or a peer dependency.

For reference, here are the relevant parts of my package.json:

```
"dependencies": {
    "react": "16.4.0",
    "react-dom": "16.4.0",
    "react-hash-route": "1.1.0",
    "react-redux": "5.0.7",
    "react-scripts": "1.1.4",
    "redux-easy": "2.7.0"
  }
```

**Comment by mvolkmann** [comment]
Interesting. In version 2.7.0, which is the latest version, package.json has redux-mock-store listed in devDependencies. Is that what you see?

**Comment by VoltiSubito** [comment]
I see it in the redux-easy devDependency list, but those won't install when I list redux-easy as a dependency.

**Comment by mvolkmann** [comment]
I see. I'm in a bit of pickle. ;-) I don't want to make that be a regular dependency, but I use it in redux-easy.js so the setup function and do something different when it is being run from a test. I think the correct fix is to refactor the code so that redux-easy.js doesn't do anything different for tests. But that may take a while to work out. The quick fix is to just make redux-mock-store be a regular dependency for now. Do you think I should do that?

**Comment by VoltiSubito** [comment]
I agree that refactoring it out would be the ideal fix.  Don't worry about a quick fix on my account.  I added redux-mock-store as a dev dependency in my project as a work-around.

**Comment by mvolkmann** [comment]
I believe version 2.7.1 of redux-easy fixes this. Let me know if it doesn't.

**Comment by VoltiSubito** [comment]
2.7.1 fixed it.  Thanks!
