### ISSUE TITLE
Selectively exclude items from session storage.

### ISSUE THREAD

**Issue by VoltiSubito** [mvolkmann/redux-easy#4]
redux-easy places everything in the store in session storage, which is OK in most situations.  Some data might be sensitive and shouldn't be allowed to be cached or otherwise be in an "at rest" state on the end user's browser.  Some examples would include passwords or SSNs.

**Comment by mvolkmann** [comment]
Great idea! Let's enhance redux-easy to allow registering two functions named "replacer" and "reviver", utilizing names already used by the JavaScript JSON API. The "replacer" function, if provided, will be passed the current state data and what it returns will be written to session storage instead of the current state data. On a browser refresh the "reviver" function, if provided, will be passed the data from session storage and what it returns will be used to replace the current state data.

**Comment by mvolkmann** [comment]
The options object passed to `reduxEasy` can now contain `replacerFn` and `reviverFn` properties. Both are passed a state object. If they wish to change the data, they should create a new state object and not modify the one passed in. `replacerFn` is called on state before it is saved in `sessionStorage`. One use is to remove or modify sensitive data. `reviverFn` is called on state after it is retrieved from `sessionStorage`. One use is to restore or modify sensitive data.
