### ISSUE TITLE
using derived values in mapStateToProps ?

### ISSUE THREAD

**Issue by wvlia5** [mvolkmann/redux-easy#6]
There is only an example on how to map a path of the state to props, but what if I need to compute some derived value from the state to pass as a prop?

**Comment by mvolkmann** [comment]
Not sure if this is what you are looking for, so let me know if it isn't. One way to accomplish this is with getDerivedStateFromProps. For example, suppose I have a prop named "message" and I want compute "msgLength" from it. I could do something like this.

```js
import React, {Component} from 'react';
import {watch} from 'redux-easy';

class Card extends Component {
  state = {
    msgLength: 0
  };

  static getDerivedStateFromProps(props) {
     return {msgLength: props.message.length};
  }

  render() {
    return (
      <div>
        {this.props.message} ({this.state.msgLength})
      </div>
    );
  }
}

export default watch(Card, {message: ''});
```

**Comment by wvlia5** [comment]
yes, it is!
I'm considering other options:
1) I think in this circumstance you can also ditch `watch` and just use `connect` with a `mapStateToProps` function only.
2) Move the computation to `render` instead of `getDerivedStateFromProps` as recommended [here](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#what-about-memoization)

I think the benefit of 1 is to separate the state mapping from the component (maybe the data present in the state is conceptually unrelated to component props). Do you recommend the solution you suggested instead?

**Comment by mvolkmann** [comment]
The reason I prefer my watch function over using mapStateToProps is that it feels like overkill to require developers to write a function in each component that uses state to pull out the state values they want. With my watch function I can just provide a list of the paths I care about ... no extra function needed.

I think hooks are really the way to go for computing values derived from state. I find them easier that using getDerivedStateFromProps. I have some pretty good notes on hooks that you can find here: https://github.com/mvolkmann/talks/blob/master/react-hooks.key.pdf.

I have another library that is similar to redux-easy that I like even more. See https://www.npmjs.com/package/context-easy. It uses the Context API instead of Redux and doesn't require the use of mapStateToProps or a watch function.

**Comment by wvlia5** [comment]
perfect, thanks! i'm taking a look
